repos:
  # Core file and syntax checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: end-of-file-fixer
        exclude: ^node_modules/
      - id: trailing-whitespace
      - id: check-added-large-files
        exclude: ^tests/data/
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: check-xml
      - id: debug-statements
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: mixed-line-ending
      - id: requirements-txt-fixer

  # Modern Python linting and formatting with Ruff
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.12
    hooks:
      # Linter
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      # Formatter (replaces black)
      - id: ruff-format

  # Type checking
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.17.1
    hooks:
      - id: mypy
        additional_dependencies: ["types-PyYAML", "pandas-stubs"]
        args:
          [--ignore-missing-imports, --no-strict-optional, --allow-untyped-defs]

  # Security scanning
  - repo: https://github.com/PyCQA/bandit
    rev: 1.8.6
    hooks:
      - id: bandit
        args: [-r, --exclude, "tests"]

  # Dependency vulnerability scanning
  - repo: https://github.com/Lucas-C/pre-commit-hooks-safety
    rev: v1.4.2
    hooks:
      - id: python-safety-dependencies-check
        files: requirements.*\.txt$

  # Secrets detection
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        args: ["--baseline", ".secrets.baseline"]
        exclude: (package.lock.json|node_modules/)

  # YAML/JSON formatting (removing Docker-dependent hooks for container environment)
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        files: \.(yaml|yml|json|md)$
        exclude: ^(tests/data/|node_modules/)
