version: '3.9'

services:
  parser:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        INSTALL_DEV: "true"
    container_name: fin-parser-dev
    volumes:
      - .:/app
    env_file:
      - .env
    working_dir: /app
